FROM rust:1-bookworm@sha256:59037199c44290f2befcdd58dcc540164763fc296950255aaefeef096a1866b0 AS builder
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates git protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/openmls/openmls.git /src/openmls && cd /src/openmls && git checkout 4f407c45857d177e7b5933d32795307b4f14b196
WORKDIR /src/openmls/interop_client
COPY tools/mls-interop/Cargo.lock /src/openmls/Cargo.lock
RUN cargo build --release --locked
FROM debian:bookworm-slim@sha256:3783cc01769c7b2b1b83a5c5ad96c815348e28ed7da68e2e3687004faa906251
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates netcat-openbsd && rm -rf /var/lib/apt/lists/*
COPY --from=builder /src/openmls/target/release/interop_client /usr/local/bin/interop_client
COPY --from=builder /src/openmls/LICENSE /usr/share/doc/openmls/LICENSE
ENTRYPOINT ["/usr/local/bin/interop_client"]
